<a href="https://colab.research.google.com/github/Aswin1910/Sentiment-driven-recom/blob/main/Sentiment_driven_recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset1 = pd.read_csv('appliance_reviews.csv')

In [ ]:
import gzip
import json

def parse(path):
    with gzip.open(path, 'rt', encoding='utf-8') as g:
        for l in g:
            yield json.loads(l)

def get_df(path, max_rows=5000):
    data = []
    for i, d in enumerate(parse(path)):
        if i >= max_rows:
            break
        data.append(d)
    return pd.DataFrame(data)

df = get_df("Appliances.jsonl.gz")
df[['rating', 'title', 'text', 'user_id','asin']].dropna().to_csv("dataset.csv", index=False)


In [ ]:
import numpy as np
dataset = pd.read_csv('dataset.csv')
dataset.head()

rating              title  \
0     5.0         Work great   
1     5.0  excellent product   
2     5.0    Happy customer!   
3     5.0      Amazing value   
4     5.0        Dryer parts   

                                                text  \
0              work great. use a new one every month   
1                            Little on the thin side   
2                   Quick delivery, fixed the issue!   
3  I wasn't sure whether these were worth it or n...   
4  Easy to install got the product expected to re...   

                        user_id        asin  
0  AGKHLEW2SOWHNMFQIJGBECAF7INQ  B01N0TQ0OH  
1  AHWWLSPCJMALVHDDVSUGICL6RUCA  B07DD2DMXB  
2  AHZIJGKEWRTAEOZ673G5B3SNXEGQ  B082W3Z9YK  
3  AFGUPTDFAWOHHL4LZDV27ERDNOYQ  B078W2BJY8  
4  AELFJFAXQERUSMTXJQ6SYFFRDWMA  B08C9LPCQV

In [ ]:
#Train


import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus1 = []
for i in range(0, 5000):
  review = re.sub('[^a-zA-Z]', ' ', dataset1['review_text'][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  all_stopwords.remove("didn't")
  all_stopwords.remove("doesn't")
  all_stopwords.remove("don't")
  all_stopwords.remove("hasn't")
  all_stopwords.remove("haven't")
  all_stopwords.remove("isn't")
  all_stopwords.remove("wasn't")
  all_stopwords.remove("weren't")
  all_stopwords.remove("won't")
  all_stopwords.remove("wouldn't")
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus1.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
print(corpus1)

['highli recommend applianc', 'great build qualiti function', 'highli recommend applianc', 'great build qualiti function', 'great build qualiti function', 'product excel work perfectli', 'product excel work perfectli', 'product excel work perfectli', 'great build qualiti function', 'highli recommend applianc', 'amaz experi use', 'amaz experi use', 'product excel work perfectli', 'satisfi qualiti perform', 'amaz experi use', 'highli recommend applianc', 'amaz experi use', 'satisfi qualiti perform', 'product excel work perfectli', 'amaz experi use', 'great build qualiti function', 'great build qualiti function', 'satisfi qualiti perform', 'highli recommend applianc', 'product excel work perfectli', 'amaz experi use', 'amaz experi use', 'amaz experi use', 'great build qualiti function', 'satisfi qualiti perform', 'highli recommend applianc', 'highli recommend applianc', 'great build qualiti function', 'product excel work perfectli', 'product excel work perfectli', 'great build qualiti fun

In [ ]:
#APPLIANCES


import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 5000):
  if isinstance(dataset['text'][i], str):
    review = re.sub('[^a-zA-Z]', ' ', dataset['text'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')
    all_stopwords.remove("didn't")
    all_stopwords.remove("doesn't")
    all_stopwords.remove("don't")
    all_stopwords.remove("hasn't")
    all_stopwords.remove("haven't")
    all_stopwords.remove("isn't")
    all_stopwords.remove("wasn't")
    all_stopwords.remove("weren't")
    all_stopwords.remove("won't")
    all_stopwords.remove("wouldn't")
    review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
    review = ' '.join(review)
    corpus.append(review)
  else:
    corpus.append('')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
print(corpus)

['work great use new one everi month', 'littl thin side', 'quick deliveri fix issu', 'sure whether worth not given cost compar origin brand filter br br happili report great valu work everi bit good origin fenc worri whether worth assur', 'easi instal got product expect receiv', 'buy ice machin month ago use time per month leak bad use anymor compani refus replac', 'not best qualiti', 'part came quickli fit lg dryer thank', 'alway arriv fast manner descript line accur help', 'compani respond quickli refund purchas price right away problem unit not work tri ev', 'love littl kitchen gadget would recommend', 'havent long year road may chang mind love blue trim didnt realiz match shower curtain well not solid pretti swirl purpl blue match nice got first one broken return replac im impress quiet like tht agit thing get stuck', 'k concern wouldnt fit perfect', 'im excit see coffe come got mason jar order nd one alway fridg summer br br updat first cup bit strong ad way much coffe guess water

In [ ]:
len(corpus)

5000

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X_train = cv.fit_transform(corpus1).toarray()
y_train = dataset1.iloc[:, -1].values

In [ ]:
print(y_train)

[4 5 5 ... 2 2 1]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
X_test = cv.transform(corpus).toarray()
y_test = dataset.iloc[:, 0].values

In [ ]:
print(y_test)

[5. 5. 5. ... 4. 5. 5.]


In [ ]:
y_test[0]

np.float64(5.0)

In [ ]:
for i in range(0,5000):
   if int(y_test[i]) >= 3:
       y_test[i] = 1
   else:
      y_test[i] = 0

In [ ]:
y_test = y_test.astype(int)

In [ ]:
print(y_test[0])

1


In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

array([4, 5, 5, ..., 2, 5, 5])

In [ ]:
y_pred1=np.zeros(5000)

In [ ]:
for i in range(0,5000):
   if int(y_pred[i]) >= 4:
       y_pred1[i] = 1
   else:
      y_pred1[i] = 0
print(np.concatenate((y_pred1.reshape(len(y_pred1),1), y_test.reshape(len(y_pred),1)),1))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [0. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#APPLIANCES(title)


import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 5000):
  if isinstance(dataset['text'][i], str):
    review = re.sub('[^a-zA-Z]', ' ', dataset['title'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')
    all_stopwords.remove("didn't")
    all_stopwords.remove("doesn't")
    all_stopwords.remove("don't")
    all_stopwords.remove("hasn't")
    all_stopwords.remove("haven't")
    all_stopwords.remove("isn't")
    all_stopwords.remove("wasn't")
    all_stopwords.remove("weren't")
    all_stopwords.remove("won't")
    all_stopwords.remove("wouldn't")
    review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
    review = ' '.join(review)
    corpus.append(review)
  else:
    corpus.append('')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
X_testt = cv.transform(corpus).toarray()
y_testt = dataset.iloc[:, 0].values

In [ ]:
y_predd=classifier.predict(X_testt)

In [ ]:
y_predd1 = np.zeros(5000)

In [ ]:
for i in range(0,5000):
   if int(y_predd[i]) >= 4:
       y_predd1[i] = 1
   else:
      y_predd1[i] = 0
print(np.concatenate((y_predd1.reshape(len(y_predd1),1), y_test.reshape(len(y_predd1),1)),1))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
print(y_pred1)
print(y_predd1)

[1. 1. 1. ... 0. 1. 1.]
[1. 1. 1. ... 1. 1. 1.]


In [ ]:
y_pred1 = y_pred1 + y_predd1

In [ ]:
for i in range(0,5000):
   if int(y_pred1[i]) > 0:
       y_pred1[i] = 1

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test[:len(y_pred1)], y_pred1)
print(cm)
accuracy_score(y_test[:len(y_pred1)], y_pred1)

[[ 125  421]
 [  86 4368]]


0.8986

In [ ]:
dataset['upd'] = dataset['rating']*0.6 + y_pred*0.08

In [ ]:
dataset_sorted = dataset.sort_values(by='upd', ascending=False)

In [ ]:
dataset_sorted

rating                                              title  \
7        1.0                                         Five Stars   
4999     1.0                                          Quick fix   
8        1.0                                         Five Stars   
1        1.0                                  excellent product   
2        1.0                                    Happy customer!   
...      ...                                                ...   
4269     0.0                                     Waste of money   
4239     0.0                                   It’s a no for me   
137      0.0  Rinses dishes....lovely,. could have saved  mo...   
37       0.0                                         Poor value   
6        0.0                            They don't fit properly   

                                                   text  \
7       Part came quickly and fit my LG dryer.  Thanks!   
4999                                          very nice   
8     Always arrive in a fast manner.  Descriptions ...   
1                               Little on the thin side   
2                      Quick delivery, fixed the issue!   
...                                                 ...   
4269  Said they would fit my refrigerator and the ar...   
4239  These are terrible. They make the water taste ...   
137   Not worth the price.  Takes up too much space,...   
37                            Does not fit in same hole   
6                                  Not the best quality   

                           user_id        asin   upd  
7     AH6PLOGWYIVIWLJTY756BHNFD4YA  B00AF7WZTM  1.00  
4999  AE2FSM3CYL5L6GYJOBHYMWV66FAA  B0921424L1  1.00  
8     AGCIVNDDRX3PXIUINEG4NCRGWCRA  B001H05AXY  1.00  
1     AHWWLSPCJMALVHDDVSUGICL6RUCA  B07DD2DMXB  1.00  
2     AHZIJGKEWRTAEOZ673G5B3SNXEGQ  B082W3Z9YK  1.00  
...                            ...         ...   ...  
4269  AH2TLCCPMYSYZBFSFBLS2ZJWKBWA  B00ZY6KM4E  0.08  
4239  AFTKDRD5CXVX6EFU64DZ4PDCSRJQ  B07K1G1GD3  0.08  
137   AHRQPBQJJ2PJET5WBJIKNLAFHHSA  B089YD3Z91  0.08  
37    AE2TA5GQH4JI5RQ4W5H5PQOVYBGA  B00ECV6EEO  0.08  
6     AHCV2CNCOCG6WECDROOUYPDZIFEQ  B001TH7GZA  0.08  

[5000 rows x 6 columns]